# Generated by Django 4.2.15 on 2024-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_emp_count_app', '0002_alter_companyinfo_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='current_employee_estimate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='total_employee_estimate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='year_founded',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
