# Generated by Django 4.2.15 on 2024-09-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_emp_count_app', '0005_alter_companyinfo_current_employee_estimate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
